projects_folder = '<full-path-to-projects-folder>'
debug = true
merges = false

[[projects]]
project_folder = '<project-folder-1>'
source_branch = '<source-branch-project-1>'
target_branch = '<target-branch-project-1>'

[[projects]]
project_folder = '<project-folder-2>'
source_branch = '<source-branch-project-2>'
target_branch = '<target-branch-project-2>'

