log_level = "info"

[[projects]]
name = 'git-without-diff'
folder = '/tmp/git-without-diff'
source_branch = 'featureA'

[[projects]]
name = 'git-with-diff'
folder = '/tmp/git-with-diff'
source_branch = 'featureA'

[[projects]]
name = 'git-with-diff-on-merge'
folder = '/tmp/git-with-diff-on-merge'
source_branch = 'featureA'
remote_name = 'upstream'
