name: release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
      - run: sudo apt -y install mingw-w64 
      - run: cargo build --release
      - run: cargo build --release --target=x86_64-pc-windows-gnu
      - run: ls target/release/
      - run: ls target/x86_64-pc-windows-gnu/release
        
